# Dockerfile.web
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN python -m venv /venv \
 && /venv/bin/pip install --upgrade pip \
 && /venv/bin/pip install -r requirements.txt

COPY . .

ENV FLASK_APP=app
ENV FLASK_ENV=development

EXPOSE 5050

CMD ["/venv/bin/flask", "run", "--host=0.0.0.0", "--port=5050"]
