version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onepager-backend
    ports:
      - "5055:5000"  # local:container
    volumes:
      - ./backend:/app  # for live code changes

  frontend:
    image: python:3.10-slim
    container_name: onepager-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: python3 -m http.server 3000
    ports:
      - "3010:3000"
